export const FETCH_SHIP_STYLES_START = 'FETCH_SHIP_STYLES_START';
export const FETCH_SHIP_STYLES_FAIL = 'FETCH_SHIP_STYLES_FAIL';
export const FETCH_SHIP_STYLES_SUCCESS= 'FETCH_SHIP_STYLES_SUCCESS';

export const FETCH_SHIPS_BY_PARAM_START = 'FETCH_SHIPS_BY_PARAM';
export const FETCH_SHIPS_BY_PARAM_FAIL = 'FETCH_SHIPS_BY_PARAM';
export const FETCH_SHIPS_BY_PARAM_SUCCESS = 'FETCH_SHIPS_BY_PARAM';