export const FETCH_FILTERS_START = 'FETCH_FILTERS_START';
export const FETCH_FILTERS_FAIL = 'FETCH_FILTERS_FAIL';
export const FETCH_FILTERS_SUCCESS= 'FETCH_FILTERS_SUCCESS';

export const FETCH_SHIPS_BY_PARAM_START = 'FETCH_SHIPS_BY_PARAM';
export const FETCH_SHIPS_BY_PARAM_FAIL = 'FETCH_SHIPS_BY_PARAM';
export const FETCH_SHIPS_BY_PARAM_SUCCESS = 'FETCH_SHIPS_BY_PARAM';

export const FETCH_WEAPONS_BY_PARAM_START = 'FETCH_WEAPONS_BY_PARAM';
export const FETCH_WEAPONS_BY_PARAM_FAIL = 'FETCH_WEAPONS_BY_PARAM';
export const FETCH_WEAPONS_BY_PARAM_SUCCESS = 'FETCH_WEAPONS_BY_PARAM';

export const SELECT_SHIP = 'SELECT_SHIP';

export const PAGINTATION_HANDLER = 'PAGINATION_HANDLER';